version: '3'

services:

  web:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    build:
      dockerfile: ./php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  cron:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db